title: "Protokoll [Datum]"
labels: "documentation"
body:
  - type: markdown
    attributes:
      value: |
        Agenda:
          * Begrüßung
          * Status-Update zum Projektfortschritt
          * Diskussion von offenen Aufgaben
          * Neue Anforderungen oder Änderungen 
          * Aufgabenverteilung
          * Termin für das nächste Treffen
          * Sonstiges
  - type: textarea
    id: teilnehmer
    attributes:
      label: Teilnehmer
      description: "Wer hat am Meeting teilgenommen?"
      value: |
        1.
        2.
        3.
        ...
      render: markdown
    validations:
      required: true
  - type: textarea
    id: offeneAufgaben
    attributes:
      label: Offene Aufgaben
      description: "[Beschreibung] [#IssueNr] - [evtl. Erklärung]"
      value: |
        1.
        2.
      render: markdown
    validations:
      required: false
  - type: textarea
    id: aenderungen
    attributes:
      label: Neue Anforderungen/Änderungen
      description: "[Beschreibung] [#IssueNr]"
      value: |
        1.
        2.
      render: markdown
  - type: textarea
    id: aufgabenverteilung
    attributes:
      label: Aufgabenverteilung
      description: "[#Issue] [Person/en]"
      value: |
        * 
        * 
      render: markdown
  - type: markdown
    attributes:
      value: |
        Nächstes Termin
  - type: textarea
    id: beschluesse
    attributes:
      label: Beschlüsse
      description: ""
      value: |
        1.
        2.
      render: markdown
    validations:
      required: false
  - type: textarea
    id: notizen
    attributes:
      label: Notizen
      description: 
      value: |
      render: markdown
    validations:
      required: false
  - type: dropdown
    id: tag
    attributes:
      label: "Tag"
      options:
        - Mo
        - Di
        - Mi
        - Do
        - Fr
        - Sa
        - So
  - type: input
    attributes:
      label: "Datum"
