title: "Protokoll [Datum]"
labels: "documentation"
body:
  - type: markdown
    attributes:
      value: |
        Agenda:
          * Begrüßung
          * Status-Update zum Projektfortschritt
          * Diskussion von offenen Aufgaben
          * Neue Anforderungen oder Änderungen 
          * Aufgabenverteilung
          * Termin für das nächste Treffen
          * Sonstiges
  - type: textarea
    id: teilnehmer
    attributes:
      label: Teilnehmer
      description: "Wer hat am Meeting teilgenommen?"
      value: |
        1.
        2.
        3.
        ...
      render: markdown
    validations:
      required: true
  - type: textarea
    id: offeneAufgaben
    attributes:
      label: Offene Aufgaben
      description: "Was wurde nicht gemacht, bzw. woran muss man weiter arbeiten?"
      value: |
        1.
        2.
      render: markdown
    validations:
      required: false
  - type: textarea
     id: aenderungen
    attributes:
      label: Neue Anforderungen/Änderungen
      description: "Hier kommen neue Issues rein"
      value: |
        1.
        2.
      render: markdown
        
