title: "Statusreport [Datum]"
labels: "documentation"
body:
  - type: dropdown
    id: status
    attributes:
      label: "Status"
      options:
        - 🟢
        - 🟡
        - 🔴
  - type: textarea
    id: Quicktakes
    attributes:
      label: ⚡Quicktakes
      description: "Status in Kurze"
      value: |
        * 
        * 
        ...
    validations:
      required: true
  - type: textarea
    id: Achievements
    attributes:
      label: 🥇 Achievements
      description: "Unsere Achievements"
      value: |
        * 
        * 
        ...
    validations:
      required: true
  - type: textarea
    id: nextSteps
    attributes:
      label: 🗺️ Next Steps
      description: "Die nächsten Schritte"
      value: |
        * 
        * 
        ...
    validations:
      required: true
  - type: textarea
    id: tabelle
    attributes:
      label: Zeitaufwand
      description: Zeitaufwände
      value: |
      First Header  | Second Header
      ------------- | -------------
      Content Cell  | Content Cell
      Content Cell  | Content Cell
