title: "Statusreport [Datum]"
labels: "documentation"
body:
  - type: dropdown
    id: status
    attributes:
      label: "Status"
      options:
        - 🟢
        - 🟡
        - 🔴
  - type: textarea
    id: Quicktakes
    attributes:
      label: Teilnehmer
      description: "Status in Kurze"
      value: |
        ## ⚡ Quicktakes
        * 
        * 
        ...
      render: markdown
    validations:
      required: true
