title: "Statusreport [Datum]"
labels: "documentation"
body:
  - type: dropdown
    id: status
    attributes:
      label: "Status"
      options:
        - 🟢
        - 🟡
        - 🔴
  - type: textarea
    id: Quicktakes
    attributes:
      label: ⚡Quicktakes
      description: "Status in Kurze"
      value: |
        * 
        * 
        ...
    validations:
      required: true
  - type: textarea
    id: Achievements
    attributes:
      label: 🥇 Achievements
      description: "Unsere Achievements"
      value: |
        * 
        * 
        ...
    validations:
      required: true
  - type: textarea
    id: nextSteps
    attributes:
      label: 🗺️ Next Steps
      description: "Die nächsten Schritte"
      value: |
        * 
        * 
        ...
    validations:
      required: true
  - type: textarea
    id: table
    attributes:
      label: 🕑 Zeiterfassung
      description: Zeiterfassung
      value: |
        | -------- | Requirements |  Design  | Projektmanagement | Implementierung | Sonstiges |
        |----------|--------------|----------|-------------------|-----------------|-----------|
        | Anisa    |              |          |                   |                 |           |
        | Elnaz    |              |          |                   |                 |           |
        | Marc     |              |          |                   |                 |           |
        | Matej    |              |          |                   |                 |           |
        | Simon    |              |          |                   |                 |           |
    validations:
      required: true
  - type: textarea
    id: branches
    attributes:
      label: Veränderte Branches
      description: "Diese Branches wurden geändert"
      value: |
        * 
        * 
    validations:
      required: true
